sudo: required
language: python
dist: xenial # required for Python >= 3.7 # Travis CI website
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt # command to install dependencies
  - pip install .
script:
  - pytest # command to run tests
#  - make test # alternate test setup
#  - python setup.py test # flask-split example
